sudo: required
services:
  - docker

before_install:
  - docker build -t sapta94/myapp -f Dockerfile.dev .

script:
  - docker run -e CI=true sapta94/myapp npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-349772406588"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access-key
  secret_access_key: $secret-key
